<?xml version="1.0"?>
<robot name="jackal" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Namespace argument for multi-robot support -->
  <xacro:arg name="robot_namespace" default="" />
  <xacro:property name="robot_namespace" value="$(arg robot_namespace)" />
  <!-- Add underscore separator if namespace is not empty -->
  <xacro:property name="ns_prefix" value="${robot_namespace + '_' if robot_namespace else ''}" />
  
  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:property name="wheelbase" value="0.262" />
  <xacro:property name="track" value="0.37559" />
  <xacro:property name="wheel_vertical_offset" value="0.0345" />
  <xacro:property name="footprint_vertical_offset" value="-0.0655" />

  <xacro:property name="wheel_radius" value="0.098" />
  <xacro:property name="wheel_width" value="0.040" />

  <xacro:property name="chassis_length" value="0.420" />
  <xacro:property name="chassis_width" value="0.310" />
  <xacro:property name="chassis_height" value="0.184" />

  <xacro:property name="dummy_inertia" value="1e-09"/>

  <xacro:property name="mount_spacing" value="0.120" />

  <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0" /></material>
  <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0" /></material>
  <material name="yellow"><color rgba="0.8 0.8 0.0 1.0" /></material>
  <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>

  <xacro:macro name="wheel" params="prefix *joint_pose">

    <link name="${ns_prefix}${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <mesh filename="package://swarm_description/meshes/jackal-wheel.stl"/>
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.477"/>
        <inertia
          ixx="0.0013" ixy="0" ixz="0"
          iyy="0.0024" iyz="0"
          izz="0.0013"/>
      </inertial>
    </link>

    <gazebo reference="${ns_prefix}${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
      <selfCollide>false</selfCollide>
      <mu1 value="0.5"/>
      <mu2 value="0.5"/>
      <kp value="10000000.0" />
      <kd value="1" />
      <fdir1 value="1 0 0"/>
    </gazebo>

    <joint name="${ns_prefix}${prefix}_wheel" type="continuous">
      <parent link="${ns_prefix}chassis_link"/>
      <child link="${ns_prefix}${prefix}_wheel_link" />
      <xacro:insert_block name="joint_pose" />
      <axis xyz="0 1 0" />
    </joint>

    <!-- In reality, Jackal has only two motors, one per side. However, it's more
         straightforward for Gazebo to simulate as if there's an actuator per wheel. -->
    
  </xacro:macro>

  <xacro:wheel prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>

  <link name="${ns_prefix}base_link"></link>

  <joint name="${ns_prefix}base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="${ns_prefix}base_link"/>
    <child link="${ns_prefix}chassis_link" />
  </joint>

  <link name="${ns_prefix}chassis_link">
    <visual>
      <origin xyz="0 0 ${footprint_vertical_offset}" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <mesh filename="package://swarm_description/meshes/jackal-base.stl"/>
      </geometry>
      <material name="dark_grey" />
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <!-- Center of mass -->
      <origin xyz="0.012  0.002 0.067" rpy="0 0 0"/>
      <mass value="16.523"/>
      <!-- Moments of inertia: ( chassis without wheels ) -->
      <inertia
        ixx="0.3136" ixy="-0.0008" ixz="0.0164"
        iyy="0.3922" iyz="-0.0009"
        izz="0.4485"/>
      </inertial>
  </link>

  <xacro:unless value="$(optenv JACKAL_FRONT_ACCESSORY_FENDER 0)">
    <link name="${ns_prefix}front_fender_link">
      <visual>
        <geometry>
          <mesh filename="package://swarm_description/meshes/jackal-fender.stl"/>
        </geometry>
        <material name="yellow" />
      </visual>
    </link>
  </xacro:unless>

  <xacro:if value="$(optenv JACKAL_FRONT_ACCESSORY_FENDER 0)">
    <link name="${ns_prefix}front_fender_link">
      <visual>
        <geometry>
          <mesh filename="package://swarm_description/meshes/accessory_fender.stl"/>
        </geometry>
        <material name="yellow" />
      </visual>
    </link>

    <link name="${ns_prefix}front_fender_accessory_link"/>
    <joint name="${ns_prefix}front_fender_accessory_joint" type="fixed">
      <origin xyz="0.25629 0 0.07455" rpy="${PI} 0 0" />
      <parent link="${ns_prefix}front_fender_link" />
      <child link="${ns_prefix}front_fender_accessory_link" />
    </joint>
  </xacro:if>

  <joint name="${ns_prefix}front_fender_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="${ns_prefix}chassis_link" />
    <child link="${ns_prefix}front_fender_link" />
  </joint>

  <xacro:unless value="$(optenv JACKAL_REAR_ACCESSORY_FENDER 0)">
    <link name="${ns_prefix}rear_fender_link">
      <visual>
        <geometry>
          <mesh filename="package://swarm_description/meshes/jackal-fender.stl"/>
        </geometry>
        <material name="yellow" />
      </visual>
    </link>
  </xacro:unless>

  <xacro:if value="$(optenv JACKAL_REAR_ACCESSORY_FENDER 0)">
    <link name="${ns_prefix}rear_fender_link">
      <visual>
        <geometry>
          <mesh filename="package://swarm_description/meshes/accessory_fender.stl"/>
        </geometry>
        <material name="yellow" />
      </visual>
    </link>

    <link name="${ns_prefix}rear_fender_accessory_link"/>
    <joint name="${ns_prefix}rear_fender_accessory_joint" type="fixed">
      <origin xyz="0.25629 0 0.07455" rpy="${PI} 0 0" />
      <parent link="${ns_prefix}rear_fender_link" />
      <child link="${ns_prefix}rear_fender_accessory_link" />
    </joint>
  </xacro:if>

  <joint name="${ns_prefix}rear_fender_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
    <parent link="${ns_prefix}chassis_link" />
    <child link="${ns_prefix}rear_fender_link" />
  </joint>

  <!-- Default Internal IMU Link -->
  <link name="${ns_prefix}imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
    </inertial>
  </link>
  <joint name="${ns_prefix}imu_joint" type="fixed">
    <parent link="${ns_prefix}chassis_link" />
    <child link="${ns_prefix}imu_link" />
  </joint>

  <!-- Default LIDAR Link -->
  <link name="${ns_prefix}lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.0508" length="0.055"/>
      </geometry>
      <origin xyz="0 0 0.008" />
      <material name="black" />
    </visual>
  </link>
  <joint name="${ns_prefix}lidar_joint" type="fixed">
    <parent link="${ns_prefix}chassis_link" />
    <child link="${ns_prefix}lidar_link" />
    <origin xyz="0.0 0.0 0.205" />
  </joint>

  <link name="${ns_prefix}mid_mount"></link>
  <joint name="${ns_prefix}mid_mount_joint" type="fixed">
    <parent link="${ns_prefix}chassis_link" />
    <child link="${ns_prefix}mid_mount" />
    <origin xyz="0 0 ${chassis_height}" />
  </joint>

  <link name="${ns_prefix}rear_mount"></link>
  <joint name="${ns_prefix}rear_mount_joint" type="fixed">
    <parent link="${ns_prefix}mid_mount" />
    <child link="${ns_prefix}rear_mount" />
    <origin xyz="${-mount_spacing} 0 0" />
  </joint>

  <link name="${ns_prefix}front_mount"></link>
  <joint name="${ns_prefix}front_mount_joint" type="fixed">
    <parent link="${ns_prefix}mid_mount" />
    <child link="${ns_prefix}front_mount" />
    <origin xyz="${mount_spacing} 0 0" />
  </joint>

  <!-- Bring in simulation data for Gazebo. -->
  <xacro:include filename="$(find swarm_description)/urdf/jackal.gazebo" />

  <!-- Add the ROS2 Controller (skip if part of mobile manipulator) -->
  <xacro:arg name="standalone" default="true" />
  <xacro:if value="$(arg standalone)">
    <xacro:include filename="$(find swarm_description)/urdf/jackal_ros2_control.xacro" />
  </xacro:if>

  <!-- Optional standard accessories, including their simulation data. The rendering
       of these into the final description is controlled by optenv variables, which
       default each one to off.-->
  <xacro:include filename="$(find swarm_description)/urdf/jackal_accessories.urdf.xacro" />

  <!-- OutdoorNav -->
  <xacro:arg name="outdoornav_enabled"       default="$(optenv OUTDOORNAV_ENABLED 0)" />
  <xacro:arg name="outdoornav_configuration" default="$(optenv OUTDOORNAV_CONFIGURATION standard)" />

  <!-- OutdoorNav URDF Config -->
  <xacro:if value="$(arg outdoornav_enabled)">
    <xacro:include filename="$(find cpr_onav_description)/urdf/outdoornav_description.urdf.xacro" />
    <xacro:outdoornav_sensors outdoornav_configuration="$(arg outdoornav_configuration)" />
  </xacro:if>



</robot>