<?xml version="1.0"?>
<robot name="mobile_manipulator" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!-- Namespace argument for multi-robot support -->
  <xacro:arg name="robot_namespace" default="" />
  <xacro:property name="robot_namespace" value="$(arg robot_namespace)" />
  <!-- Add underscore separator if namespace is not empty -->
  <xacro:property name="ns_prefix" value="" />
  
  <!-- Tell jackal.urdf.xacro not to include its own ros2_control -->
  <xacro:arg name="standalone" default="false" />
  
  <!-- Include the Jackal rover base -->
  <xacro:include filename="$(find swarm_description)/urdf/jackal.urdf.xacro" />
  
  <!-- Mount position for UR5 arm on top of Jackal 
       The mid_mount is at the center of the chassis top surface
       We'll mount the UR5 arm slightly raised for better clearance -->
  <xacro:property name="arm_mount_height" value="0.01" />  <!-- 5cm above mid_mount -->
  <xacro:property name="arm_mount_x_offset" value="0.0" />  <!-- Centered in X -->
  <xacro:property name="arm_mount_y_offset" value="0.0" />  <!-- Centered in Y -->
  
  <!-- Create a mounting plate link for the UR5 arm -->
  <link name="${ns_prefix}arm_mount_plate">
    <visual>
      <origin xyz="0 0 ${-arm_mount_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.15 0.15 ${arm_mount_height}"/>
      </geometry>
      <material name="dark_grey">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${-arm_mount_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.15 0.15 ${arm_mount_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 ${-arm_mount_height/2}" rpy="0 0 0"/>
      <inertia 
        ixx="0.00875" ixy="0.0" ixz="0.0"
        iyy="0.00875" iyz="0.0"
        izz="0.015"/>
    </inertial>
  </link>
  
  <!-- Joint connecting the mounting plate to Jackal's mid_mount -->
  <joint name="${ns_prefix}arm_mount_joint" type="fixed">
    <parent link="${ns_prefix}mid_mount"/>
    <child link="${ns_prefix}arm_mount_plate"/>
    <origin xyz="${arm_mount_x_offset} ${arm_mount_y_offset} ${arm_mount_height}" rpy="0 0 0"/>
  </joint>
  
  <!-- UR5 Arm Links and Joints -->
  <!-- We need to define the UR5 arm structure inline or include it with proper parent -->
  
  <!-- UR5 Base Link mounted on the arm mounting plate -->
  <link name="${ns_prefix}ur5_base_link">
    <inertial>
      <origin xyz="-0.0033230512143046006 -0.0004232197888539764 0.037822190938846395" rpy="0 0 0"/>
      <mass value="25.3"/>
      <inertia 
          ixx="0.00671" 
          iyy="0.00671" 
          izz="0.01125" 
          ixy="-0.000188" 
          iyz="0.0" 
          ixz="0.0"
      />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>
  
  <!-- Joint connecting UR5 base to the mounting plate -->
  <joint name="${ns_prefix}ur5_mount_joint" type="fixed">
    <parent link="${ns_prefix}arm_mount_plate"/>
    <child link="${ns_prefix}ur5_base_link"/>
    <origin xyz="0 0 -0.025" rpy="0 0 0"/>
  </joint>

  <!-- UR5 Link 1 -->
  <link name="${ns_prefix}ur5_link1_1">
    <inertial>
      <origin xyz="-5.118812714607554e-06 0.016411047782836283 0.05864433019110279" rpy="0 0 0"/>
      <mass value="1.667428920912541"/>
      <inertia ixx="0.004178" iyy="0.003273" izz="0.003817" ixy="0.0" iyz="-0.000173" ixz="1e-06"/>
    </inertial>
    <visual>
      <origin xyz="0.003691 5.6e-05 -0.050586" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link1_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <origin xyz="0.003691 5.6e-05 -0.050586" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link1_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <joint name="${ns_prefix}ur5_base_link1_joint" type="continuous">
    <origin xyz="-0.003691 -5.6e-05 0.050586" rpy="0 0 0"/>
    <parent link="${ns_prefix}ur5_base_link"/>
    <child link="${ns_prefix}ur5_link1_1"/>
    <axis xyz="0.0 -0.0 1.0"/>
  </joint>

  <!-- UR5 Link 2 Part 1 -->
  <link name="${ns_prefix}ur5_link2_p1_1">
    <inertial>
      <origin xyz="6.203040415705269e-06 0.06207005674361077 0.007860389181770538" rpy="0 0 0"/>
      <mass value="1.5524700894200791"/>
      <inertia ixx="0.003628" iyy="0.003009" izz="0.003383" ixy="-1e-06" iyz="-0.000207" ixz="-0.0"/>
    </inertial>
    <visual>
      <origin xyz="0.003691 -0.075244 -0.110286" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link2_p1_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <origin xyz="0.003691 -0.075244 -0.110286" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link2_p1_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <joint name="${ns_prefix}ur5_link1_link2p1_joint" type="continuous">
    <origin xyz="0.0 0.0753 0.0597" rpy="0 0 0"/>
    <parent link="${ns_prefix}ur5_link1_1"/>
    <child link="${ns_prefix}ur5_link2_p1_1"/>
    <axis xyz="0.0 -1.0 -0.0"/>
  </joint>

  <!-- UR5 Link 2 Part 2 -->
  <link name="${ns_prefix}ur5_link2_p2_1">
    <inertial>
      <origin xyz="-8.752471172565526e-05 2.4376620175181607e-07 0.1524996678439083" rpy="0 0 0"/>
      <mass value="1.937681145922208"/>
      <inertia ixx="0.017402" iyy="0.017402" izz="0.001914" ixy="0.0" iyz="-0.0" ixz="1e-06"/>
    </inertial>
    <visual>
      <origin xyz="0.003693 -0.142247 -0.176586" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link2_p2_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <origin xyz="0.003693 -0.142247 -0.176586" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link2_p2_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <joint name="${ns_prefix}ur5_p1_p2_joint" type="fixed">
    <origin xyz="-2e-06 0.067003 0.0663" rpy="0 0 0"/>
    <parent link="${ns_prefix}ur5_link2_p1_1"/>
    <child link="${ns_prefix}ur5_link2_p2_1"/>
  </joint>

  <!-- UR5 Link 2 Part 3 -->
  <link name="${ns_prefix}ur5_link2_p3_1">
    <inertial>
      <origin xyz="-7.763250047288905e-06 -0.004932943256389266 0.05843895228729162" rpy="0 0 0"/>
      <mass value="1.5524700894200791"/>
      <inertia ixx="0.003628" iyy="0.003009" izz="0.003383" ixy="1e-06" iyz="0.000207" ixz="-0.0"/>
    </inertial>
    <visual>
      <origin xyz="0.003704 -0.142247 -0.481586" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link2_p3_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <origin xyz="0.003704 -0.142247 -0.481586" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link2_p3_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <joint name="${ns_prefix}ur5_p2_p3_joint" type="fixed">
    <origin xyz="-1.1e-05 0.0 0.305" rpy="0 0 0"/>
    <parent link="${ns_prefix}ur5_link2_p2_1"/>
    <child link="${ns_prefix}ur5_link2_p3_1"/>
  </joint>

  <!-- UR5 Link 3 -->
  <link name="${ns_prefix}ur5_link3_1">
    <inertial>
      <origin xyz="0.17378102072172863 -0.04787490591742441 0.00100186606907815" rpy="0 0 0"/>
      <mass value="2.846539405621545"/>
      <inertia ixx="0.003063" iyy="0.061797" izz="0.062318" ixy="0.003731" iyz="2.2e-05" ixz="-0.000342"/>
    </inertial>
    <visual>
      <origin xyz="0.003706 -0.075244 -0.547886" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link3_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <origin xyz="0.003706 -0.075244 -0.547886" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link3_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <joint name="${ns_prefix}ur5_link2p3_link3_joint" type="continuous">
    <origin xyz="-2e-06 -0.067003 0.0663" rpy="0 0 0"/>
    <parent link="${ns_prefix}ur5_link2_p3_1"/>
    <child link="${ns_prefix}ur5_link3_1"/>
    <axis xyz="0.0 -1.0 -0.0"/>
  </joint>

  <!-- UR5 Link 4 -->
  <link name="${ns_prefix}ur5_link4_1">
    <inertial>
      <origin xyz="2.12490884528016e-05 0.04182917130330904 -0.003987177325129543" rpy="0 0 0"/>
      <mass value="0.5732810659722621"/>
      <inertia ixx="0.000753" iyy="0.000581" izz="0.000587" ixy="0.0" iyz="1.1e-05" ixz="0.0"/>
    </inertial>
    <visual>
      <origin xyz="-0.388538 -0.063244 -0.550142" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link4_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <origin xyz="-0.388538 -0.063244 -0.550142" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link4_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <joint name="${ns_prefix}ur5_link3_link4_joint" type="continuous">
    <origin xyz="0.392244 -0.012 0.002256" rpy="0 0 0"/>
    <parent link="${ns_prefix}ur5_link3_1"/>
    <child link="${ns_prefix}ur5_link4_1"/>
    <axis xyz="0.0 1.0 -0.0"/>
  </joint>

  <!-- UR5 Link 5 -->
  <link name="${ns_prefix}ur5_link5_1">
    <inertial>
      <origin xyz="-0.003851364362202292 4.3924354040825175e-05 0.04240877360333983" rpy="0 0 0"/>
      <mass value="0.5732811937839646"/>
      <inertia ixx="0.000597" iyy="0.000754" izz="0.000572" ixy="1e-06" iyz="0.0" ixz="2e-05"/>
    </inertial>
    <visual>
      <origin xyz="-0.388441 -0.116864 -0.591692" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link5_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <origin xyz="-0.388441 -0.116864 -0.591692" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link5_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <joint name="${ns_prefix}ur5_link4_link5_joint" type="continuous">
    <origin xyz="-9.7e-05 0.05362 0.04155" rpy="0 0 0"/>
    <parent link="${ns_prefix}ur5_link4_1"/>
    <child link="${ns_prefix}ur5_link5_1"/>
    <axis xyz="-0.00232 0.0 0.999997"/>
  </joint>

  <!-- UR5 Link 6 -->
  <link name="${ns_prefix}ur5_link6_1">
    <inertial>
      <origin xyz="0.01818377138506838 -7.537991570427671e-05 0.0001621667781095404" rpy="0 0 0"/>
      <mass value="0.1747134109193075"/>
      <inertia ixx="0.000123" iyy="8.2e-05" izz="8.3e-05" ixy="-0.0" iyz="0.0" ixz="-0.0"/>
    </inertial>
    <visual>
      <origin xyz="-0.429865 -0.116512 -0.645408" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link6_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <origin xyz="-0.429865 -0.116512 -0.645408" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find swarm_description)/meshes/link6_1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <joint name="${ns_prefix}ur5_link5_link6_joint" type="continuous">
    <origin xyz="0.041424 -0.000352 0.053716" rpy="0 0 0"/>
    <parent link="${ns_prefix}ur5_link5_1"/>
    <child link="${ns_prefix}ur5_link6_1"/>
    <axis xyz="0.999962 -0.008461 0.00232"/>
  </joint>

  <!-- Gazebo tags for UR5 links -->
  <gazebo reference="${ns_prefix}ur5_base_link">
    <material>Gazebo/Silver</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <self_collide>true</self_collide>
    <gravity>true</gravity>
  </gazebo>

  <gazebo reference="${ns_prefix}ur5_link1_1">
    <material>Gazebo/Silver</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <self_collide>true</self_collide>
  </gazebo>

  <gazebo reference="${ns_prefix}ur5_link2_p1_1">
    <material>Gazebo/Silver</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <self_collide>true</self_collide>
  </gazebo>

  <gazebo reference="${ns_prefix}ur5_link2_p2_1">
    <material>Gazebo/Silver</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <self_collide>true</self_collide>
  </gazebo>

  <gazebo reference="${ns_prefix}ur5_link2_p3_1">
    <material>Gazebo/Silver</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <self_collide>true</self_collide>
  </gazebo>

  <gazebo reference="${ns_prefix}ur5_link3_1">
    <material>Gazebo/Silver</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <self_collide>true</self_collide>
  </gazebo>

  <gazebo reference="${ns_prefix}ur5_link4_1">
    <material>Gazebo/Silver</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <self_collide>true</self_collide>
  </gazebo>

  <gazebo reference="${ns_prefix}ur5_link5_1">
    <material>Gazebo/Silver</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <self_collide>true</self_collide>
  </gazebo>

  <gazebo reference="${ns_prefix}ur5_link6_1">
    <material>Gazebo/Silver</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <self_collide>true</self_collide>
  </gazebo>

  <!-- ROS2 Control for Mobile Manipulator -->
  <ros2_control name="MobileManipulatorSystem" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>
    
    <!-- Jackal Wheel Joints -->
    <joint name="${ns_prefix}front_left_wheel">
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>
    <joint name="${ns_prefix}front_right_wheel">
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>
    <joint name="${ns_prefix}rear_left_wheel">
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>
    <joint name="${ns_prefix}rear_right_wheel">
      <command_interface name="velocity"/>
      <state_interface name="velocity"/>
      <state_interface name="position"/>
    </joint>
    
    <!-- UR5 Arm Joints -->
    <joint name="${ns_prefix}ur5_base_link1_joint">
      <command_interface name="position">
        <param name="min">-6.28</param>
        <param name="max">6.28</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <joint name="${ns_prefix}ur5_link1_link2p1_joint">
      <command_interface name="position">
        <param name="min">-6.28</param>
        <param name="max">6.28</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <joint name="${ns_prefix}ur5_link2p3_link3_joint">
      <command_interface name="position">
        <param name="min">-6.28</param>
        <param name="max">6.28</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <joint name="${ns_prefix}ur5_link3_link4_joint">
      <command_interface name="position">
        <param name="min">-6.28</param>
        <param name="max">6.28</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <joint name="${ns_prefix}ur5_link4_link5_joint">
      <command_interface name="position">
        <param name="min">-6.28</param>
        <param name="max">6.28</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <joint name="${ns_prefix}ur5_link5_link6_joint">
      <command_interface name="position">
        <param name="min">-6.28</param>
        <param name="max">6.28</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

</robot>
